# version: "3.9"

# services:
#   postgres_dwh:
#     image: postgres:16-alpine
#     container_name: nafad_dwh
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: dwh
#       POSTGRES_USER: dwh_user
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./schema:/docker-entrypoint-initdb.d
#       - ./data:/data
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U dwh_user -d dwh"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   pgdata:
version: "3.9"

services:
  postgres_dwh:
    image: postgres:16-alpine
    container_name: nafad_dwh
    restart: unless-stopped
    environment:
      POSTGRES_DB: dwh
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
      - ./data:/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dwh_user -d dwh"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    image: postgres:16-alpine
    container_name: nafad_etl
    depends_on:
      postgres_dwh:
        condition: service_healthy
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./etl:/etl
      - ./data:/data
    entrypoint: >
      sh -c "
        echo '=== ETL NAFAD PAY ===' &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/00_create_staging.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/01_load_csv.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/02_populate_dim_date.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/03_populate_dim_user.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/04_populate_dim_merchant.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/05_populate_dim_agency.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/06_load_transactions_csv.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/07_populate_fact_transactions.sql &&
        psql -h postgres_dwh -U dwh_user -d dwh -f /etl/08_validation_checks.sql &&
        echo '=== ETL TERMINE ==='
      "
    profiles:
      - etl

  metabase:
    image: metabase/metabase:latest
    container_name: nafad_metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      postgres_dwh:
        condition: service_healthy

volumes:
  pgdata:
