-- ============================================================
-- NAFAD PAY G4 — Création des tables staging temporaires
-- Description : Tables temporaires pour charger les CSV bruts
-- ============================================================

DROP TABLE IF EXISTS tmp_users;
DROP TABLE IF EXISTS tmp_merchants;
DROP TABLE IF EXISTS tmp_agencies;
DROP TABLE IF EXISTS tmp_transactions;

CREATE TABLE tmp_users (
    id                  BIGINT,
    nni                 VARCHAR,
    first_name          VARCHAR,
    last_name           VARCHAR,
    full_name           VARCHAR,
    gender              VARCHAR,
    birth_date          VARCHAR,
    ethnicity           VARCHAR,
    phone               VARCHAR,
    email               VARCHAR,
    wilaya_id           INT,
    wilaya_name         VARCHAR,
    moughataa_id        INT,
    moughataa_name      VARCHAR,
    profile_type        VARCHAR,
    kyc_level           VARCHAR,
    status              VARCHAR,
    device_type         VARCHAR,
    registration_date   VARCHAR,
    last_login          VARCHAR,
    created_at          VARCHAR,
    updated_at          VARCHAR
);

CREATE TABLE tmp_merchants (
    id                  BIGINT,
    code                VARCHAR,
    mcc                 VARCHAR,
    name                VARCHAR,
    category_code       VARCHAR,
    category_label      VARCHAR,
    owner_first_name    VARCHAR,
    owner_last_name     VARCHAR,
    owner_full_name     VARCHAR,
    owner_gender        VARCHAR,
    owner_ethnicity     VARCHAR,
    phone               VARCHAR,
    email               VARCHAR,
    wilaya_id           INT,
    wilaya_name         VARCHAR,
    moughataa_id        INT,
    moughataa_name      VARCHAR,
    address             VARCHAR,
    latitude            VARCHAR,
    longitude           VARCHAR,
    commission_rate     VARCHAR,
    avg_transaction_min VARCHAR,
    avg_transaction_max VARCHAR,
    status              VARCHAR,
    registration_date   VARCHAR,
    created_at          VARCHAR,
    updated_at          VARCHAR
);

CREATE TABLE tmp_agencies (
    id                  BIGINT,
    code                VARCHAR,
    name                VARCHAR,
    wilaya_id           INT,
    wilaya_name         VARCHAR,
    moughataa_id        INT,
    moughataa_name      VARCHAR,
    address             VARCHAR,
    latitude            VARCHAR,
    longitude           VARCHAR,
    phone               VARCHAR,
    email               VARCHAR,
    opening_hours       VARCHAR,
    status              VARCHAR,
    tier                VARCHAR,
    float_balance       VARCHAR,
    max_float           VARCHAR,
    license_number      VARCHAR,
    license_expiry      VARCHAR,
    created_at          VARCHAR,
    updated_at          VARCHAR
);

CREATE TABLE tmp_transactions (
    id                          BIGINT,
    reference                   VARCHAR,
    idempotency_key             VARCHAR,
    transaction_type            VARCHAR,
    transaction_type_label      VARCHAR,
    amount                      VARCHAR,
    fee                         VARCHAR,
    total_amount                VARCHAR,
    currency                    VARCHAR,
    source_account_id           VARCHAR,
    source_account_number       VARCHAR,
    source_user_id              VARCHAR,
    source_user_name            VARCHAR,
    destination_account_id      VARCHAR,
    destination_account_number  VARCHAR,
    destination_user_id         VARCHAR,
    destination_user_name       VARCHAR,
    merchant_id                 VARCHAR,
    merchant_code               VARCHAR,
    merchant_name               VARCHAR,
    agency_id                   VARCHAR,
    agency_code                 VARCHAR,
    agency_name                 VARCHAR,
    agent_id                    VARCHAR,
    agent_name                  VARCHAR,
    status                      VARCHAR,
    failure_reason              VARCHAR,
    balance_before              VARCHAR,
    balance_after               VARCHAR,
    node_id                     VARCHAR,
    datacenter                  VARCHAR,
    sync_status                 VARCHAR,
    last_synced_at              VARCHAR,
    amount_node_a               VARCHAR,
    amount_node_b               VARCHAR,
    channel                     VARCHAR,
    device_type                 VARCHAR,
    ip_address                  VARCHAR,
    risk_score                  VARCHAR,
    description                 VARCHAR,
    transaction_date            VARCHAR,
    transaction_time            VARCHAR,
    created_at                  VARCHAR,
    updated_at                  VARCHAR,
    completed_at                VARCHAR
);